### PR TITLE
Increase speed, and reduce memory usage

### PR DESCRIPTION
**Pull request by GabrielHoffman**
Hi @pneuvial 
  Thanks again for the software package.  This new version is drastically faster: I can run 140K SNPS on chr22 from 1KG on a 48 core machine in 22 seconds with `h=1000`.

Updates
* Previously I had updated `matR()` and `matL()` to use RcppArmadillo. In this version I got an additional speed up by combining `matL() + rowCumsums()` in a single C++ function, plus the same for `matR() + rowCumsums()`.  This also allowed using OpenMP to distribute this work across multiple CPU cores.  This gives a dramatic performance improvement on a 48 core Linux machine.  But OpenMP is not enabled by default on OSX.  I'm not sure about Windows.

* I also optimized some code in `correct.chac()` that was a memory bottleneck.

Test failures:
* test_plotSim.R: The original adjclust doesn't pass this test on my machine.
* test_modify.R
        This test uses an unusual similarity matrix and the original code used `adjclust:::checkCondition()` to modify the matrix. Even with a sparse matrix, this check seems to be quadratic time and memory.  In my version, `checkCondition()` is not run, but can be enabled with a `strictCheck` flag.  This test assumes it is always run.  How do you want to address this?    

Best,
Gabriel

### CODE REVIEW

**Comment by GabrielHoffman** [comment]
Hi @pneuvial, I'm just checking in about this new version

Best,
Gabriel

**Comment by tuxette** [comment]
Hi Gabriel. Pierre and I have been very busy lately (end of academic year is tough) so sorry that we haven't processed your pull request already. We have scheduled to work on it next week so hopefully you'll get some feedback soon. Sorry for the late answer!
Nathalie

**Comment by tuxette** [comment]
@GabrielHoffman 
I'm on it. I have a few questions:
* about `openMP`, does that mean that the function will not work on MacOS or just that it won't distribute the computation for that OS?
* `test_plotSim.R`: if you still have it, can you post the error that you get?
* about `adjclust:::checkCondition()`, we'll check if we can improve it but it is used to prevent negative heights in the dendrogram. I would prefer have a default `strictCheck` to `TRUE` that the user can turn off if needed

**Comment by tuxette** [comment]
@GabrielHoffman 
I have difficulty reading your commit history (many have the same name and I don't understand some of them, like c07536b where several documentation files have been deleted). I want to merge features one by one to have the time to test and check them. Am I right to say that:
- I can melt commits e21af08 up to ca7d23d that correspond to the main modification where you introduced speed up of your code
- I can melt commits ad68958 up to d770033 where your implemented the GAP statistics (and that doesn't touch the previous feature)
- I can melt all the other commits that all correspond to WCSS (which are independent from the other two features)
If so, I'll do that and proceed to review one by one. Thank you for your help in this!

**Comment by GabrielHoffman** [comment]
1) OpenMP will allow parallelization on systems that allow it.  When not supported by a system, the code with run with one thread.  The user will not notice a difference besides speed.  I develop on OSX and test on Ubuntu, and there is no difference except speed

2) I didn't go into this before, because the issues are not related to my changes.  Here are the errors from v0.5.99 on CRAN.  This is on OSX, but I get the same thing on Ubuntu.

```r
# Confirm I'm using v0.5.99 from CRAN
packageVersion("adjclust")
#> [1] '0.5.99'

# show session info
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-apple-darwin19.6.0 (64-bit)
#> Running under: macOS Catalina 10.15.7
#> 
#> Matrix products: default
#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
#> LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] ps_1.6.0          digest_0.6.27     withr_2.4.1       magrittr_2.0.1   
#>  [5] reprex_2.0.0      evaluate_0.14     highr_0.8         stringi_1.5.3    
#>  [9] rlang_0.4.10      cli_2.4.0         rstudioapi_0.13   fs_1.5.0         
#> [13] rmarkdown_2.7     tools_4.0.3       stringr_1.4.0     glue_1.4.2       
#> [17] xfun_0.22         yaml_2.2.1        compiler_4.0.3    htmltools_0.5.1.1
#> [21] knitr_1.31

# run tests
library(testthat)
source("/Users/gabrielhoffman/workspace/repos/adjclust/tests/testthat/test_plotSim.R")


#> Test passed 😸
#> ── Error (test_plotSim.R:24:3): 'plotSim' works for 'dgCMatrix' ────────────────
#> Error: argument is not a matrix
#> Backtrace:
#>  1. base::t(sim) /Users/gabrielhoffman/workspace/repos/adjclust/tests/testthat/test_plotSim.R:24:2
#>  2. base::t.default(sim)


#> Test passed 😀
#> Test passed 🎉
#> ── Failure (test_plotSim.R:81:3): 'plotSim' works for 'snpStats' ───────────────
#> `plotSim(ceph.1mb)` threw an error.
#> Message: logical row selection vector is wrong length
#> Class:   simpleError/error/condition
#> Backtrace:
#>   1. testthat::expect_error(plotSim(ceph.1mb), NA) /Users/gabrielhoffman/workspace/repos/adjclust/tests/testthat/test_plotSim.R:81:2
#>   7. adjclust:::plotSim.matrix(ceph.1mb)
#>   8. adjclust:::plotSim_generic(...)
#>  10. adjclust:::extract_values.default(mat)
#>  12. mat[upper.tri(mat, diag = TRUE)]
#>  13. snpStats:::.local(x, i, j, ..., drop)
#> 
#> ── Failure (test_plotSim.R:83:3): 'plotSim' works for 'snpStats' ───────────────
#> `plotSim(ceph.1mb, h = 100, stats = "D.prime", xaxis = TRUE)` threw an error.
#> Message: logical row selection vector is wrong length
#> Class:   simpleError/error/condition
#> Backtrace:
#>   1. testthat::expect_error(...) /Users/gabrielhoffman/workspace/repos/adjclust/tests/testthat/test_plotSim.R:83:2
#>   7. adjclust:::plotSim.matrix(...)
#>   8. adjclust:::plotSim_generic(...)
#>  10. adjclust:::extract_values.default(mat)
#>  12. mat[upper.tri(mat, diag = TRUE)]
#>  13. snpStats:::.local(x, i, j, ..., drop)
```

The first error can be fixed by adding `library(Matrix)` to `test_plotSim.R`.  The others are related to the behavior of a `SnpMatrix` object with this code: https://github.com/pneuvial/adjclust/blob/07d5d38b591be833e6d81555848aebb042b812db/R/plotSim.R#L83


3) I will make `strictCheck = TRUE` default and add it to the user end function.  I'll push this in a hour once I do some more checks

Gabriel

**Comment by tuxette** [comment]
OK for 1. and 2.: thanks!
For 3. I'll handle it during the merge. Do not bother about it.

**Comment by GabrielHoffman** [comment]
I'm not going to make any changes until I hear back.

I realize my commit history I not ideal.  I developed on my Mac, but then tested in a big dataset on Ubuntu.  So each code test has its own commit so I could pull the code to the Ubuntu machine.  I should have used another branch.  This makes understanding each commit just about impossible.  

I cleaned up some code in https://github.com/pneuvial/adjclust/pull/47/commits/f730bf98f03053d5932124b67570c445e1495970 : I removed the GAP/WCSS code since. I meant that to be development, but its in the wrong branch. I added `strictCheck` (I'd already done it when I saw your message, and updated `NEWS` and `DESCRIPTION` 

I think the easiest way to manage this is to diff my https://github.com/pneuvial/adjclust/pull/47/commits/f730bf98f03053d5932124b67570c445e1495970 with the branch I started with https://github.com/pneuvial/adjclust/commit/07d5d38b591be833e6d81555848aebb042b812db

**Comment by tuxette** [comment]
OK. I was checking things and testing (btw, I have no error in tests on my computer / ubuntu also) but the best (I think) is just take your new changes and remade the test from your last commit (it seems clearer now). I'll perform the merge into one single commit: that will be easier I think.

**Comment by tuxette** [comment]
@GabrielHoffman OK it's done. I have a few more minor things to fix before we can submit it to CRAN but I'll take care of that another day (next week probably: it should not be too long). Thanks a lot for your help!
Also, if you want to make another pull request for GAP statistics or else, no problem but either make only one by feature or make less commits by features if you can (so it's easier to review and understand for us).

**Comment by GabrielHoffman** [comment]
Thanks!  I just installed the new version and confirmed the speed up works.

**Comment by GabrielHoffman** [comment]
Hi, I'm just following up to see about pushing this to CRAN

Best,
Gabriel

**Comment by tuxette** [comment]
Hi Gabriel! We're doing our best but it's unlikely that we will be able to handle that before our return from summer holidays.
Regards,
Nathalie

**Comment by pneuvial** [comment]
Hi Gabriel,

adjclust v0.6.3 is on its way to CRAN!

Many thanks for your contributions!

Best,

Pierre

**Pull request merged**
